# This workflow runs actions to pull, build, and run tacent unit tests.

name: Unit Tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # The buildrunwindows job builds and runs unit tests on windows.
  checkoutbuildrunwindows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    # - name: Run a one-line script
    #   run: echo Hello, world!

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     echo Add other actions to build,
    #     echo test, and deploy your project.
      
    # Use msbuild to build the VS solution
    - name: Build Solution
      run: |
        # cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
        # .\MSBuild.exe $Env:GITHUB_WORKSPACE\UnitTests\Windows\UnitTests.sln
        # dir
        echo 'Building Solution'
        & 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe' $Env:GITHUB_WORKSPACE\UnitTests\Windows\UnitTests.sln
        echo 'Done Building Solution'
    
    - name: Unit Tests
      run: |
        echo 'Running Unit Tests'
        cd UnitTests
        .\UnitTests.exe
        echo 'Done Running Unit Tests'
      
